name: app_garb
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  cloud_firestore: ^5.6.7
  get: ^4.7.2
  firebase_storage: ^12.4.5
  image_picker: ^1.1.2
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  uuid: ^4.5.1
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.0.0
  percent_indicator: ^4.2.5
  flutter_sound: ^9.28.0
  just_audio: ^0.10.3
  permission_handler: ^12.0.0+1
  path_provider: ^2.1.5
  audioplayers: ^6.4.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/fondo_community.jpg
    - assets/profile_images/avatar1.png
    - assets/profile_images/avatar2.png
    - assets/profile_images/avatar3.png
    - assets/profile_images/avatar4.png
    - assets/profile_images/avatar5.png
