// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5b56NLs7PZMCxg5t4o7MpWer-fXFUF-k',
    appId: '1:749432688229:web:d035f123d9b8f234a4808c',
    messagingSenderId: '749432688229',
    projectId: 'proyecto-game-65267',
    authDomain: 'proyecto-game-65267.firebaseapp.com',
    storageBucket: 'proyecto-game-65267.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyVh6eXMFSuL8SJNHUQ4u-AImOcA8LbPU',
    appId: '1:749432688229:android:a2adcc9f9b5f65dfa4808c',
    messagingSenderId: '749432688229',
    projectId: 'proyecto-game-65267',
    storageBucket: 'proyecto-game-65267.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmu8Udo3C0wnursKRBdQoUAfaA9H1EchU',
    appId: '1:749432688229:ios:0f2773a2443dedb4a4808c',
    messagingSenderId: '749432688229',
    projectId: 'proyecto-game-65267',
    storageBucket: 'proyecto-game-65267.firebasestorage.app',
    iosBundleId: 'com.example.appGarb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmu8Udo3C0wnursKRBdQoUAfaA9H1EchU',
    appId: '1:749432688229:ios:0f2773a2443dedb4a4808c',
    messagingSenderId: '749432688229',
    projectId: 'proyecto-game-65267',
    storageBucket: 'proyecto-game-65267.firebasestorage.app',
    iosBundleId: 'com.example.appGarb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5b56NLs7PZMCxg5t4o7MpWer-fXFUF-k',
    appId: '1:749432688229:web:4354dbfdfa629496a4808c',
    messagingSenderId: '749432688229',
    projectId: 'proyecto-game-65267',
    authDomain: 'proyecto-game-65267.firebaseapp.com',
    storageBucket: 'proyecto-game-65267.firebasestorage.app',
  );
}
